--- 
title: "Understanding Sampling"
author: "Lingyun Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
links-as-notes: true
colorlinks: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preface {-}

How do you learn, or to be exact, how do you learn complex stuff? I guess that many different answers will come up, because we are all different in many aspects, such as culture background, knowledge level, and learning style etc. etc.. For myself, if I want to seriously learn some complex stuff, then I will write about it. Without doubts, *Sampling* is complex, and it is kind of boring, but it is important (for me, because I need it for my work at Stats NZ, and for you the reasons must be different). So, I have to learn and re-learn sampling, and now I am writing about it.

Since I work for Stats NZ, I will use contexts and examples at there. Chapter 1 introduces preliminary concepts, such as *population*, *target population*, *survey populaton*, *simple random sample*, *stratified sample*, *cluster sample*, and *systematic sample*. Chapter 1 also presents the knowledge about New Zealand, which is required for sampling design at Stats NZ. Chapter 2 is about *sampling design*; Chapter 3 is about *weighting system*; Chapter 4 covers how to estimate *sampling errors*. Chapter 4 briefly introduces software for sampling.


# Preliminary concepts and knowledge

## Concepts

## Knowledge about NZ


# Sampling design

# Weighting system

# Sampling error

# Software
